version: '3.8'

services:
  habitos-postgres:
    image: postgres:13
    container_name: habitos-postgres
    restart: always
    ports:
      - "5434:5432" 
    environment:
      POSTGRES_DB: habitosdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - habitos_pgdata:/var/lib/postgresql/data

volumes:
  habitos_pgdata:
