version: '3.8'

services:
  habitos-retos:
    build:
      context: .
    container_name: habitos_retos
    ports:
      - '8081:8081' 
    environment:
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_DDL_AUTO=${SPRING_JPA_DDL_AUTO}
      - SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
      - SPRING_JPA_DIALECT=${SPRING_JPA_DIALECT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_KEY_TIME_EXP=${JWT_KEY_TIME_EXP}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_CONSUMER_GROUP_ID=${KAFKA_CONSUMER_GROUP_ID}
      - KAFKA_AUTO_OFFSET_RESET=${KAFKA_AUTO_OFFSET_RESET}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    env_file:
      - .env
    networks:
      - devNetworkArq
    restart: unless-stopped

networks:
  devNetworkArq:
    external: true
